export const Currencies = async () => {

    const response = await fetch("https://api.monegoo.com/currencies", { cache: 'no-store' });
    const result = await response.json();

    
    let timestamp = new Date(result.timestamp * 1000).toUTCString()

    return (
        <div style={{textAlign: 'center'}}>
                <h2 className="leading-tighter font-heading mb-6 text-5xl font-bold tracking-tighter md:text-4xl">Currency Rates</h2>
                <h4 className="leading-tighter font-heading mb-6 tracking-tighter text-lg"><span>{timestamp}</span></h4>
                <table className="prose" style={{marginLeft: 'auto', marginRight: 'auto', width: '100%'}}>
                    <tbody>
                    <tr>
                        <td>AED/USD</td>
                        <td>{result.data.AED}</td>
                    </tr>
                    <tr>
                        <td>AFN/USD</td>
                        <td>{result.data.AFN}</td>
                    </tr>
                    <tr>
                        <td>ALL/USD</td>
                        <td>{result.data.ALL}</td>
                    </tr>
                    <tr>
                        <td>AMD/USD</td>
                        <td>{result.data.AMD}</td>
                    </tr>
                    <tr>
                        <td>ANG/USD</td>
                        <td>{result.data.ANG}</td>
                    </tr>
                    <tr>
                        <td>AOA/USD</td>
                        <td>{result.data.AOA}</td>
                    </tr>
                    <tr>
                        <td>ARS/USD</td>
                        <td>{result.data.ARS}</td>
                    </tr>
                    <tr>
                        <td>AUD/USD</td>
                        <td>{result.data.AUD}</td>
                    </tr>
                    <tr>
                        <td>AWG/USD</td>
                        <td>{result.data.AWG}</td>
                    </tr>
                    <tr>
                        <td>AZN/USD</td>
                        <td>{result.data.AZN}</td>
                    </tr>
                    <tr>
                        <td>BAM/USD</td>
                        <td>{result.data.BAM}</td>
                    </tr>
                    <tr>
                        <td>BBD/USD</td>
                        <td>{result.data.BBD}</td>
                    </tr>
                    <tr>
                        <td>BDT/USD</td>
                        <td>{result.data.BDT}</td>
                    </tr>

                    <tr>
                        <td>BGN/USD</td>
                        <td>{result.data.BGN}</td>
                    </tr>
                    <tr>
                        <td>BIF/USD</td>
                        <td>{result.data.BIF}</td>
                    </tr>
                    <tr>
                        <td>BMD/USD</td>
                        <td>{result.data.BMD}</td>
                    </tr>
                    <tr>
                        <td>BND/USD</td>
                        <td>{result.data.BND}</td>
                    </tr>
                    <tr>
                        <td>BOB/USD</td>
                        <td>{result.data.BOB}</td>
                    </tr>
                    <tr>
                        <td>BRL/USD</td>
                        <td>{result.data.BRL}</td>
                    </tr>
                    <tr>
                        <td>BSD/USD</td>
                        <td>{result.data.BSD}</td>
                    </tr>
                    <tr>
                        <td>BTC/USD</td>
                        <td>{result.data.BTC}</td>
                    </tr>
                    <tr>
                        <td>BTN/USD</td>
                        <td>{result.data.BTN}</td>
                    </tr>
                    <tr>
                        <td>BWP/USD</td>
                        <td>{result.data.BWP}</td>
                    </tr>
                    <tr>
                        <td>BYN/USD</td>
                        <td>{result.data.BYN}</td>
                    </tr>
                    <tr>
                        <td>BZD/USD</td>
                        <td>{result.data.BZD}</td>
                    </tr>
                    <tr>
                        <td>CAD/USD</td>
                        <td>{result.data.CAD}</td>
                    </tr>
                    <tr>
                        <td>CDF/USD</td>
                        <td>{result.data.CDF}</td>
                    </tr>
                    <tr>
                        <td>CHF/USD</td>
                        <td>{result.data.CHF}</td>
                    </tr>
                    <tr>
                        <td>CLF/USD</td>
                        <td>{result.data.CLF}</td>
                    </tr>
                    <tr>
                        <td>CLP/USD</td>
                        <td>{result.data.CLP}</td>
                    </tr>
                    <tr>
                        <td>CNH/USD</td>
                        <td>{result.data.CNH}</td>
                    </tr>
                    <tr>
                        <td>CNY/USD</td>
                        <td>{result.data.CNY}</td>
                    </tr>
                    <tr>
                        <td>COP/USD</td>
                        <td>{result.data.COP}</td>
                    </tr>
                    <tr>
                        <td>CRC/USD</td>
                        <td>{result.data.CRC}</td>
                    </tr>
                    <tr>
                        <td>CUC/USD</td>
                        <td>{result.data.CUC}</td>
                    </tr>
                    <tr>
                        <td>CUP/USD</td>
                        <td>{result.data.CUP}</td>
                    </tr>
                    <tr>
                        <td>CVE/USD</td>
                        <td>{result.data.CVE}</td>
                    </tr>
                    <tr>
                        <td>CZK/USD</td>
                        <td>{result.data.CZK}</td>
                    </tr>
                    <tr>
                        <td>DJF/USD</td>
                        <td>{result.data.DJF}</td>
                    </tr>
                    <tr>
                        <td>DKK/USD</td>
                        <td>{result.data.DKK}</td>
                    </tr>
                    <tr>
                        <td>DOP/USD</td>
                        <td>{result.data.DOP}</td>
                    </tr>
                    <tr>
                        <td>DZD/USD</td>
                        <td>{result.data.DZD}</td>
                    </tr>
                    <tr>
                        <td>EGP/USD</td>
                        <td>{result.data.EGP}</td>
                    </tr>
                    <tr>
                        <td>ERN/USD</td>
                        <td>{result.data.ERN}</td>
                    </tr>
                    <tr>
                        <td>ETB/USD</td>
                        <td>{result.data.ETB}</td>
                    </tr>
                    <tr>
                        <td>EUR/USD</td>
                        <td>{result.data.EUR}</td>
                    </tr>
                    <tr>
                        <td>FJD/USD</td>
                        <td>{result.data.FJD}</td>
                    </tr>
                    <tr>
                        <td>FKP/USD</td>
                        <td>{result.data.FKP}</td>
                    </tr>
                    <tr>
                        <td>GBP/USD</td>
                        <td>{result.data.GBP}</td>
                    </tr>
                    <tr>
                        <td>GEL/USD</td>
                        <td>{result.data.GEL}</td>
                    </tr>
                    <tr>
                        <td>GGP/USD</td>
                        <td>{result.data.GGP}</td>
                    </tr>
                    <tr>
                        <td>GHS/USD</td>
                        <td>{result.data.GHS}</td>
                    </tr>
                    <tr>
                        <td>GIP/USD</td>
                        <td>{result.data.GIP}</td>
                    </tr>
                    <tr>
                        <td>GMD/USD</td>
                        <td>{result.data.GMD}</td>
                    </tr>
                    <tr>
                        <td>GNF/USD</td>
                        <td>{result.data.GNF}</td>
                    </tr>
                    <tr>
                        <td>GTQ/USD</td>
                        <td>{result.data.GTQ}</td>
                    </tr>
                    <tr>
                        <td>GYD/USD</td>
                        <td>{result.data.GYD}</td>
                    </tr>
                    <tr>
                        <td>HKD/USD</td>
                        <td>{result.data.HKD}</td>
                    </tr>
                    <tr>
                        <td>HNL/USD</td>
                        <td>{result.data.HNL}</td>
                    </tr>
                    <tr>
                        <td>HRK/USD</td>
                        <td>{result.data.HRK}</td>
                    </tr>
                    <tr>
                        <td>HTG/USD</td>
                        <td>{result.data.HTG}</td>
                    </tr>
                    <tr>
                        <td>HUF/USD</td>
                        <td>{result.data.HUF}</td>
                    </tr>
                    <tr>
                        <td>IDR/USD</td>
                        <td>{result.data.IDR}</td>
                    </tr>
                    <tr>
                        <td>ILS/USD</td>
                        <td>{result.data.ILS}</td>
                    </tr>
                    <tr>
                        <td>IMP/USD</td>
                        <td>{result.data.IMP}</td>
                    </tr>
                    <tr>
                        <td>INR/USD</td>
                        <td>{result.data.INR}</td>
                    </tr>
                    <tr>
                        <td>IQD/USD</td>
                        <td>{result.data.IQD}</td>
                    </tr>
                    <tr>
                        <td>IRR/USD</td>
                        <td>{result.data.IRR}</td>
                    </tr>
                    <tr>
                        <td>ISK/USD</td>
                        <td>{result.data.ISK}</td>
                    </tr>
                    <tr>
                        <td>JEP/USD</td>
                        <td>{result.data.JEP}</td>
                    </tr>
                    <tr>
                        <td>JMD/USD</td>
                        <td>{result.data.JMD}</td>
                    </tr>
                    <tr>
                        <td>JOD/USD</td>
                        <td>{result.data.JOD}</td>
                    </tr>
                    <tr>
                        <td>JPY/USD</td>
                        <td>{result.data.JPY}</td>
                    </tr>
                    <tr>
                        <td>KES/USD</td>
                        <td>{result.data.KES}</td>
                    </tr>
                    <tr>
                        <td>KGS/USD</td>
                        <td>{result.data.KGS}</td>
                    </tr>
                    <tr>
                        <td>KHR/USD</td>
                        <td>{result.data.KHR}</td>
                    </tr>
                    <tr>
                        <td>KMF/USD</td>
                        <td>{result.data.KMF}</td>
                    </tr>
                    <tr>
                        <td>KPW/USD</td>
                        <td>{result.data.KPW}</td>
                    </tr>
                    <tr>
                        <td>KRW/USD</td>
                        <td>{result.data.KRW}</td>
                    </tr>
                    <tr>
                        <td>KWD/USD</td>
                        <td>{result.data.KWD}</td>
                    </tr>
                    <tr>
                        <td>KYD/USD</td>
                        <td>{result.data.KYD}</td>
                    </tr>
                    <tr>
                        <td>KZT/USD</td>
                        <td>{result.data.KZT}</td>
                    </tr>
                    <tr>
                        <td>LAK/USD</td>
                        <td>{result.data.LAK}</td>
                    </tr>
                    <tr>
                        <td>LBP/USD</td>
                        <td>{result.data.LBP}</td>
                    </tr>
                    <tr>
                        <td>LKR/USD</td>
                        <td>{result.data.LKR}</td>
                    </tr>
                    <tr>
                        <td>LRD/USD</td>
                        <td>{result.data.LRD}</td>
                    </tr>
                    <tr>
                        <td>LSL/USD</td>
                        <td>{result.data.LSL}</td>
                    </tr>
                    <tr>
                        <td>LYD/USD</td>
                        <td>{result.data.LYD}</td>
                    </tr>
                    <tr>
                        <td>MAD/USD</td>
                        <td>{result.data.MAD}</td>
                    </tr>
                    <tr>
                        <td>MDL/USD</td>
                        <td>{result.data.MDL}</td>
                    </tr>
                    <tr>
                        <td>MGA/USD</td>
                        <td>{result.data.MGA}</td>
                    </tr>
                    <tr>
                        <td>MKD/USD</td>
                        <td>{result.data.MKD}</td>
                    </tr>
                    <tr>
                        <td>MMK/USD</td>
                        <td>{result.data.MMK}</td>
                    </tr>
                    <tr>
                        <td>MNT/USD</td>
                        <td>{result.data.MNT}</td>
                    </tr>
                    <tr>
                        <td>MOP/USD</td>
                        <td>{result.data.MOP}</td>
                    </tr>
                    <tr>
                        <td>MRU/USD</td>
                        <td>{result.data.MRU}</td>
                    </tr>
                    <tr>
                        <td>MUR/USD</td>
                        <td>{result.data.MUR}</td>
                    </tr>
                    <tr>
                        <td>MVR/USD</td>
                        <td>{result.data.MVR}</td>
                    </tr>
                    <tr>
                        <td>MWK/USD</td>
                        <td>{result.data.MWK}</td>
                    </tr>
                    <tr>
                        <td>MXN/USD</td>
                        <td>{result.data.MXN}</td>
                    </tr>
                    <tr>
                        <td>MYR/USD</td>
                        <td>{result.data.MYR}</td>
                    </tr>
                    <tr>
                        <td>MZN/USD</td>
                        <td>{result.data.MZN}</td>
                    </tr>
                    <tr>
                        <td>NAD/USD</td>
                        <td>{result.data.NAD}</td>
                    </tr>
                    <tr>
                        <td>NGN/USD</td>
                        <td>{result.data.NGN}</td>
                    </tr>
                    <tr>
                        <td>NIO/USD</td>
                        <td>{result.data.NIO}</td>
                    </tr>
                    <tr>
                        <td>NOK/USD</td>
                        <td>{result.data.NOK}</td>
                    </tr>
                    <tr>
                        <td>NPR/USD</td>
                        <td>{result.data.NPR}</td>
                    </tr>
                    <tr>
                        <td>NZD/USD</td>
                        <td>{result.data.NZD}</td>
                    </tr>
                    <tr>
                        <td>OMR/USD</td>
                        <td>{result.data.OMR}</td>
                    </tr>
                    <tr>
                        <td>PAB/USD</td>
                        <td>{result.data.PAB}</td>
                    </tr>
                    <tr>
                        <td>PEN/USD</td>
                        <td>{result.data.PEN}</td>
                    </tr>
                    <tr>
                        <td>PGK/USD</td>
                        <td>{result.data.PGK}</td>
                    </tr>
                    <tr>
                        <td>PHP/USD</td>
                        <td>{result.data.PHP}</td>
                    </tr>
                    <tr>
                        <td>PKR/USD</td>
                        <td>{result.data.PKR}</td>
                    </tr>
                    <tr>
                        <td>PLN/USD</td>
                        <td>{result.data.PLN}</td>
                    </tr>
                    <tr>
                        <td>PYG/USD</td>
                        <td>{result.data.PYG}</td>
                    </tr>
                    <tr>
                        <td>QAR/USD</td>
                        <td>{result.data.QAR}</td>
                    </tr>
                    <tr>
                        <td>RON/USD</td>
                        <td>{result.data.RON}</td>
                    </tr>
                    <tr>
                        <td>RSD/USD</td>
                        <td>{result.data.RSD}</td>
                    </tr>
                    <tr>
                        <td>RUB/USD</td>
                        <td>{result.data.RUB}</td>
                    </tr>
                    <tr>
                        <td>RWF/USD</td>
                        <td>{result.data.RWF}</td>
                    </tr>
                    <tr>
                        <td>SAR/USD</td>
                        <td>{result.data.SAR}</td>
                    </tr>
                    <tr>
                        <td>SBD/USD</td>
                        <td>{result.data.SBD}</td>
                    </tr>
                    <tr>
                        <td>SCR/USD</td>
                        <td>{result.data.SCR}</td>
                    </tr>
                    <tr>
                        <td>SDG/USD</td>
                        <td>{result.data.SDG}</td>
                    </tr>
                    <tr>
                        <td>SEK/USD</td>
                        <td>{result.data.SEK}</td>
                    </tr>
                    <tr>
                        <td>SGD/USD</td>
                        <td>{result.data.SGD}</td>
                    </tr>
                    <tr>
                        <td>SHP/USD</td>
                        <td>{result.data.SHP}</td>
                    </tr>
                    <tr>
                        <td>SLL/USD</td>
                        <td>{result.data.SLL}</td>
                    </tr>
                    <tr>
                        <td>SOS/USD</td>
                        <td>{result.data.SOS}</td>
                    </tr>
                    <tr>
                        <td>SRD/USD</td>
                        <td>{result.data.SRD}</td>
                    </tr>
                    <tr>
                        <td>SSP/USD</td>
                        <td>{result.data.SSP}</td>
                    </tr>
                    <tr>
                        <td>STD/USD</td>
                        <td>{result.data.STD}</td>
                    </tr>
                    <tr>
                        <td>STN/USD</td>
                        <td>{result.data.STN}</td>
                    </tr>
                    <tr>
                        <td>SVC/USD</td>
                        <td>{result.data.SVC}</td>
                    </tr>
                    <tr>
                        <td>SYP/USD</td>
                        <td>{result.data.SYP}</td>
                    </tr>
                    <tr>
                        <td>SZL/USD</td>
                        <td>{result.data.SZL}</td>
                    </tr>
                    <tr>
                        <td>THB/USD</td>
                        <td>{result.data.THB}</td>
                    </tr>
                    <tr>
                        <td>TJS/USD</td>
                        <td>{result.data.TJS}</td>
                    </tr>
                    <tr>
                        <td>TMT/USD</td>
                        <td>{result.data.TMT}</td>
                    </tr>
                    <tr>
                        <td>TND/USD</td>
                        <td>{result.data.TND}</td>
                    </tr>
                    <tr>
                        <td>TOP/USD</td>
                        <td>{result.data.TOP}</td>
                    </tr>
                    <tr>
                        <td>TRY/USD</td>
                        <td>{result.data.TRY}</td>
                    </tr>
                    <tr>
                        <td>TTD/USD</td>
                        <td>{result.data.TTD}</td>
                    </tr>
                    <tr>
                        <td>TWD/USD</td>
                        <td>{result.data.TWD}</td>
                    </tr>
                    <tr>
                        <td>TZS/USD</td>
                        <td>{result.data.TZS}</td>
                    </tr>
                    <tr>
                        <td>UAH/USD</td>
                        <td>{result.data.UAH}</td>
                    </tr>
                    <tr>
                        <td>UGX/USD</td>
                        <td>{result.data.UGX}</td>
                    </tr>
                    <tr>
                        <td>UYU/USD</td>
                        <td>{result.data.UYU}</td>
                    </tr>
                    <tr>
                        <td>UZS/USD</td>
                        <td>{result.data.UZS}</td>
                    </tr>
                    <tr>
                        <td>VES/USD</td>
                        <td>{result.data.VES}</td>
                    </tr>
                    <tr>
                        <td>VND/USD</td>
                        <td>{result.data.VND}</td>
                    </tr>
                    <tr>
                        <td>VUV/USD</td>
                        <td>{result.data.VUV}</td>
                    </tr>
                    <tr>
                        <td>WST/USD</td>
                        <td>{result.data.WST}</td>
                    </tr>
                    <tr>
                        <td>XAF/USD</td>
                        <td>{result.data.XAF}</td>
                    </tr>
                    <tr>
                        <td>XAG/USD</td>
                        <td>{result.data.XAG}</td>
                    </tr>
                    <tr>
                        <td>XAU/USD</td>
                        <td>{result.data.XAU}</td>
                    </tr>
                    <tr>
                        <td>XCD/USD</td>
                        <td>{result.data.XCD}</td>
                    </tr>
                    <tr>
                        <td>XDR/USD</td>
                        <td>{result.data.XDR}</td>
                    </tr>
                    <tr>
                        <td>XOF/USD</td>
                        <td>{result.data.XOF}</td>
                    </tr>
                    <tr>
                        <td>XPD/USD</td>
                        <td>{result.data.XPD}</td>
                    </tr>
                    <tr>
                        <td>XPF/USD</td>
                        <td>{result.data.XPF}</td>
                    </tr>
                    <tr>
                        <td>XPT/USD</td>
                        <td>{result.data.XPT}</td>
                    </tr>

                    <tr>
                        <td>YER/USD</td>
                        <td>{result.data.YER}</td>
                    </tr>
                    <tr>
                        <td>ZAR/USD</td>
                        <td>{result.data.ZAR}</td>
                    </tr>
                    <tr>
                        <td>ZMW/USD</td>
                        <td>{result.data.ZMW}</td>
                    </tr>
                    <tr>
                        <td>ZWL/USD</td>
                        <td>{result.data.ZWL}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
  );
} 